apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-app
        image: victorwanderley/meu-app:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 80


